### ISSUE TITLE
[UI] daily jelly / 오늘의 젤리 뷰 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS-Release#16]
## ISSUE
- daily jelly / 오늘의 젤리 뷰 구현

## To-Do
- [ ] 봉지 애니메이션 이미지 추가
- [ ] 뷰페이저 레이아웃 구현
    - [ ] item 레이아웃 구현
- [ ] 뷰페이저 스와이프 구현 
- [ ] MotionLayout으로 애니메이션 동작 구현
    - [ ] 봉지 이미지 인터렉션 종료 후 사라지도록 구현
    - [ ] 오늘의 추천활동 리스트 나타나도록 구현
- [ ] indicator 구현
- [ ] 닫기(X) 버튼 연결
