### ISSUE TITLE
[UI] explore / 탐색 뷰 구현

### ISSUE THREAD

**Issue by 0zlrlo** [Keyneez/Keyneez-AOS-Release#17]
## ISSUE
- explore / 탐색하기 뷰 구현

## To-Do
- [x] 스트링 정리
- [x] shape 추가
- [x] 필요한 이미지 다운
- [x] 전체 틀 구현
- [x] 리사이클러뷰 구현
- [x] sel 이름 수정하기
- [x] 뷰페이저 적용
- [x] shape 다시 살피기
- [x] 전체 배경색 지정하기 및 색깔 이름 바뀐 걸로 다시 지정하기
- [x] 전체적으로 dp값 조정하기
- [x] 리사이클러뷰 밑에 dp값 재조정하기
- [x] Motionlayout tapbar 적용하기
- [x] 불필요한 기존 파일들 삭제하기
- [x] regular 폰트 올라오면 수정하기
- [x] 폰트 다시 확인하기
- [x] 전체, 문화생활 이 부분을 flow로 바꾸기
- [x] 리사이클러뷰 기능 구현하기
- [x] 자바 버전 바꾸기(17로)
- [x] 탭레이아웃 수정
- [x] 그리디로 리사이클러뷰 나오게끔
- [x] 검색뷰로 버튼 연결
