### ISSUE TITLE
[UI] search / 검색 뷰 구현

### ISSUE THREAD

**Issue by 0zlrlo** [Keyneez/Keyneez-AOS-Release#18]
## ISSUE
- search / 기존 뷰 수정하기

## To-Do
- [x] 기존 윗 부분 수정
- [x] 스트링 추가 및 수정
- [x] 전반적으로 dp값 수정
- [x] 전반적으로 폰트 수정
- [x] 전반적으로 컬러 수정(전체 배경색 넣기)
- [x] contentdescription 넣기
- [x] 리사이클러뷰 최하단 dp값 넣기
- [x] Debounce(Throttle) Search 찾아보기
- [x] sel 버튼 열결하기
- [x] dispatchmotionevent(inithinekeyboard: BindingActivity의 dispatchMotionEvent 메서드 내부에서 hideKeyboard를 호출하면 다른 클릭 리스너 없이도 일괄적으로 키보드를 숨기는 이벤트를 처리할 수 있습니다!)
- [x] listadapter로 구현
- [x] 서버통신할 때 쓰는 것만 따로 model로 빼두기(Dto(data > entity)는 서버통신에 활용되는 모든 프로퍼티가 포함된 데이터 클래스에 해당합니다. UI에서 사용되는 프로퍼티만 나타낸 데이터 클래스를 domain > model에 만들어 사용해봅시다! (Dto는 서버 통신 구현할 때 추가하면 좋을 것 같습니다))
- [x] 개수 세는 flow 어떻게 할지
