### ISSUE TITLE
[UI] like / 좋아요 뷰 구현

### ISSUE THREAD

**Issue by 0zlrlo** [Keyneez/Keyneez-AOS-Release#19]
## ISSUE
- like /  좋아요 뷰 구현하기
## To-Do
- [x] 리사이클러뷰 dp 값 조정
- [x] string 추가
- [x] 삭제 버튼 만들기
- [x] 텍스트 변환하기(편집 -> 취소, 총 n개 -> n개 선택, 좋아요 -> 삭제할 활동선택)
- [x] visible->리사이클러뷰 이외의 것들
- [x] 커스텀 토스트 위치 조정하기
- [x] 삭제하기 버튼 누르면 버튼 없어지게끔 만들기
- [x] 삭제하기 버튼 누르면 텍스트 뷰 변하게끔 만들기
- [x] 바로 삭제 안되고 삭제하기 버튼 눌러야만이 삭제되게끔 하기
- [ ] 카테고리 selector 해결하기 -> 추후에 데이터바인딩으로 서버통신하는 것 하기
- [x] 체크표시 ui 이상함..수정하기
- [x] 버튼 누르는 게 뷰모델 isEdit이 true일 때만 가능하게끔하기
- [x] 바텀네비 없어지고 삭제 버튼 생기는 거 다시..
https://stackoverflow.com/questions/75183474/how-can-i-hide-my-bottom-nav-bar-on-button-pressed-flutter
- [x] 각각 항목 선택하는 것..
- [x] 삭제하는 갯수 세는 기능 구현->아이디리스트.value.size 이런 식
- [x] 삭제 하는 것....->바인딩 어댑터의 isSelected 변수 연결~(채연언니 카톡)
- [x] 아이템 선택하면 ui 바뀌는 것->각각 따로 만들어서 visibility로 처리하기
- [x] 선택했을 때 불투명+체크표시 뜨는 ui 추가
- [x] 삭제 기능
- [x] listadapter로 구현
- [x] 삭제 시 네비게이션 바 없애기
- [x] 삭제 완료 토스트 커스터마이징하기
- [x] data binding, binding adapter 쓰기
