### ISSUE TITLE
[UI] search / 검색 뷰 구현

### ISSUE THREAD

**Issue by 0zlrlo** [Keyneez/Keyneez-AOS-Release#2]
## ISSUE
- search / 검색 뷰 구현

## To-Do
- [x] drawable 다운
- [x] 본 화면 구현
- [x] 리사이클러뷰 구현
- [x] font와 color 코드 추후에 추가
- [x] shape에 해당하는 color 값 변경하기
- [x] mainactivity에서 첫 화면 다시 메인으로 바꾸기
