### ISSUE TITLE
[FEAT] main / 바텀 네비게이션 바 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS-Release#20]
## ISSUE
- main / 바텀 네비게이션 바 구현

## To-Do
- [x] bottom navigatoin bar 레이아웃 구현
- [x] menu 구현 (홈, 탐색, 좋아요, 설정)
- [x] fragment transition 구현
- [x] 뷰 확정 후 아이콘 추가 및 반영
