### ISSUE TITLE
[UI] signup / 회원가입 및 관심사 설정 레이아웃 

### ISSUE THREAD

**Issue by etama123** [Keyneez/Keyneez-AOS-Release#23]
## ISSUE
- signup/ 회원가입 및 관심사 설정 레이아웃 

## To-Do
- [ ] 온보딩 화면에 뷰페이저 적용하기
- [ ] 관심사 설정 페이지에 SharedViewModel 이용하기
- [ ] 선호 카테고리 선택시 클릭 이벤트 적용하기
