### ISSUE TITLE
[UI] detail / 상세 정보 확인 레이아웃 구현

### ISSUE THREAD

**Issue by etama123** [Keyneez/Keyneez-AOS-Release#24]
## ISSUE
- detail/ 상세 정보 확인 레이아웃 구현

## To-Do
- [x] 상세 정보 액티비티 레이아웃 구현
- [ ] 좋아요 버튼 클릭 시 색 바뀌기
- [ ] 공유 버튼 [ShareSheet](https://velog.io/@jeep_chief_14/Android%EC%97%90%EC%84%9C-%EA%B3%B5%EC%9C%A0-%EA%B8%B0%EB%8A%A5-%EB%A7%8C%EB%93%A4%EA%B8%B)  적용해보기
