### ISSUE TITLE
[CHORE] Material Design 적용

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS-Release#25]
## ISSUE
- Material Design 적용 및 안드로이드 스튜디오 버전 최적화

## To-Do
- [x] font-family 분리
- [x] appearances 보완
- [x] color system 구축
- [x] 플라밍고 최적화
- [x] 다크모드 분기 제거
