### ISSUE TITLE
[UI] home / 홈 뷰 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS-Release#29]
## ISSUE
- home / 홈 레이아웃 구현

## To-Do
- [ ] 젤리 봉투 구현 (visibility 고려)
- [ ] 이번 주의 추천 활동 ListAdapter 구현 (visibility 고려)
    - [ ] 이번 주의 추천 활동 item 레이아웃 구현
    - [ ] 이번 주의 추천 활동 어댑터 구현
- [ ] 최근에 본 활동 ListAdapter 구현
    - [ ] 최근에 본 활동 item 레이아웃 구현
    - [ ] 최근에 본 활동 어댑터 구현
