### ISSUE TITLE
[FEAT] search / 검색 뷰 기능 구현

### ISSUE THREAD

**Issue by 0zlrlo** [Keyneez/Keyneez-AOS-Release#3]
## ISSUE
- search / 검색 뷰 구현

## To-Do
- [ ] 검색 뷰 기본 기능 구현하기
- [ ] 서버 통신 하기
- [ ] dispatchmotionevent(inithinekeyboard: BindingActivity의 dispatchMotionEvent 메서드 내부에서 hideKeyboard를 호출하면 다른 클릭 리스너 없이도 일괄적으로 키보드를 숨기는 이벤트를 처리할 수 있습니다!)
- [ ] listadapter로 구현
- [ ] 서버통신할 때 쓰는 것만 따로 model로 빼두기(Dto(data > entity)는 서버통신에 활용되는 모든 프로퍼티가 포함된 데이터 클래스에 해당합니다. UI에서 사용되는 프로퍼티만 나타낸 데이터 클래스를 domain > model에 만들어 사용해봅시다! (Dto는 서버 통신 구현할 때 추가하면 좋을 것 같습니다))
- [ ] early return

**Comment by b1urrrr** [comment]
@0zlrlo 크으 빠르시네요 😲
커밋별로 나눈다고 생각하고 TO DO도 세세하게 나눠주시면 좋을 것 같아요!
세밀한 TO DO 작성을 통해 원자적 커밋을 하는 습관도 기를 수 있어요 🤭
