### ISSUE TITLE
[FEAT] search / 검색뷰 서버 통신

### ISSUE THREAD

**Issue by 0zlrlo** [Keyneez/Keyneez-AOS-Release#32]
## ISSUE
- search / 검색뷰 통신

## To-Do
- [x] 검색 뷰 서버 통신
https://github.com/GO-SOPT-ANDROID/chaeyeon-jeon/commit/5e9e42a292b0429ee84adf5ddb4bffc843d15ba8#diff-f8112c01f53cda4918224e6be27b2de3ec91e065d3295cb79cdea1802e2e8f93
- [x] 데이터바인딩 적용
- [x] 카테고리 별 색상 바뀌는 것
- [x] 배경화면 어떻게 받아 올지 여쭤보기
